### ISSUE TITLE
Translations for “Mandarin” not found because “Chinese” is searched for

### ISSUE THREAD

**Issue by GF-Huang** [Cutleast/SSE-Auto-Translator#17] opened 2024-12-03 15:17 UTC
As below, [Adamant - A Perk Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/30191) is red.

But nexusmods has Chinese/Mandarin translation.

![image](https://github.com/user-attachments/assets/f2581328-529a-4827-becd-14ba08792580)

![image](https://github.com/user-attachments/assets/76ad3252-152a-4ceb-bc86-f0ce5387f859)

**Comment by Cutleast** [comment] 2024-12-03 15:19
Could you please send us the respective log file from "SSE-AT/data/logs"?

**Comment by GF-Huang** [comment] 2024-12-03 15:25
Sure, hope this help.

[logs.zip](https://github.com/user-attachments/files/17995214/logs.zip)

**Comment by Cutleast** [comment] 2024-12-03 16:35
After being able to reproduce the issue I found out that the issue is the "Mandarin" instead of "Chinese" that's actually looked for:
![screenshot](https://github.com/user-attachments/assets/8544c6c8-b8bd-43e2-9708-c45a23dc5956)

Thanks for reporting the issue, I'll fix it for the next update!

**Comment by GF-Huang** [comment] 2024-12-03 17:19
Will you release new version recently? If not, is there any workarounds to fix this temporary?

**Comment by Cutleast** [comment] 2024-12-03 19:30
I'll try to release a fix before the end of the week. Until then, I suggest downloading those translations manually in SSE-AT. Follow these steps to download translations manually: 

1. Link SSE-AT button to Nexus Mods Mod Manager downloads by activating the button in the "Translations" tab that's looking like a chain.
2. Open the mod page of the translation and click on "Mod Manager Download" (or "Vortex Download").
3. A message should appear at the bottom of your screen, saying that the download was added to the queue.
4. The translation now gets downloaded in the "Downloads" tab in SSE-AT and installed automatically.
5. To revert "Mod Manager" downloads to MO2 or Vortex, just unlink SSE-AT by disabling the button from step 1.

**Comment by GF-Huang** [comment] 2024-12-04 04:46
> I suggest downloading those translations manually in SSE-AT

I think that is impossible, because I'm playing mod collections which has 1500+ mods. 😄 

If I modify this (as below) to `Mandarin`, then build by myself, will it work? I didn't read all source code, but I search with keyword `chinese` in this repo, this line seems to best match my guess.

https://github.com/Cutleast/SSE-Auto-Translator/blob/9b740debbfd276bceca2b1a66dff52b3313fc2f4/src/utilities/constants.py#L94-L95

**Comment by Cutleast** [comment] 2024-12-04 06:24
Yeah, that would be the correct line but you also had to change it in your configuration ("SSE-AT/data/user/config.json"), as well. The only problematic thing I see, is this: [src/processor.py#L40-L42](https://github.com/Cutleast/SSE-Auto-Translator/blob/master/src%2Fprocessor.py#L40-L42). It uses the configured language for the language detector and I don't know if it supports "Mandarin" or only "Chinese". Another side effect would be that your build would then find translations only for "Mandarin" and none for "Chinese" (though, I don't know how common they are on Nexus Mods).

**Comment by Cutleast** [comment] 2024-12-04 06:29
I rather had in mind to change this part in order to make alternatives possible (i.e. combine translations for Chinese and Mandarin): [src/translation_provider/provider.py#L235-L237](https://github.com/Cutleast/SSE-Auto-Translator/blob/master/src%2Ftranslation_provider%2Fprovider.py#L235-L237)

**Comment by GF-Huang** [comment] 2024-12-04 06:30
I found that there is no `Chinese` option but `Mandarin` for mod on nexusmod. 

From add new mod page (https://www.nexusmods.com/skyrimspecialedition/mods/add) :

![image](https://github.com/user-attachments/assets/3e639706-3988-4c9d-9121-f57f32ec08a6)

![image](https://github.com/user-attachments/assets/d12612e2-de2e-49d8-a44e-cf0a59e8c4a3)

**Comment by Cutleast** [comment] 2024-12-04 06:32
Did they change it recently? I already tested SSE-AT with Chinese back in March when v1.0 released.

**Comment by GF-Huang** [comment] 2024-12-04 06:33
I'm not sure, I just check it right now then found that. 😄

**Comment by Cutleast** [comment] 2024-12-04 06:43
So the only issue would be the language detector. As I said, I don't know if it accepts "Mandarin" or only "Chinese". In the latter case, the modlist scan would break.
Instead of changing the constant, you linked above, you could first try changing the value in your "SSE-AT/data/user/config.json" and at least the online scan should work then.

**Comment by GF-Huang** [comment] 2024-12-04 06:49
Looks like had to modify codes.

![image](https://github.com/user-attachments/assets/e49985f3-a65d-4a28-953a-d5d67e73be0e)

**Comment by GF-Huang** [comment] 2024-12-04 14:27
After these changes, I can detect `Mandarin` mods and download them, but all these mods failed while extracting.

Relative logs:
```
[04.12.2024 22:07:07.477][INFO][Downloader.download_thread]: Downloading file 'Teldryn Serious Enhanced Edition CHS-42170-7-1604897614.7z' from 'https://cf-files.nexusmods.com/cdn/1704/42170/Teldryn Serious Enhanced Edition CHS-42170-7-1604897614.7z?md5=cmARGscvYXu2vPAuDT9o6Q&expires=1733335597&user_id=232417287'...
[04.12.2024 22:07:09.285][ERROR][Archiver.extract_files]: '7z.exe' ڲⲿҲǿеĳ
ļ

[04.12.2024 22:07:09.285][ERROR][Downloader.download_thread]: Failed to import translation from downloaded archive: Unpacking command failed!
Traceback (most recent call last):
  File "C:\Users\jokeh\DEV\Code\SSE-Auto-Translator\src\database\downloads_widget.py", line 254, in download_thread
    strings = utils.import_from_archive(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jokeh\DEV\Code\SSE-Auto-Translator\src\utilities\importer.py", line 370, in import_from_archive
    archive.extract_files(plugin_files, tmp_dir)
  File "C:\Users\jokeh\DEV\Code\SSE-Auto-Translator\src\archiver\archive.py", line 147, in extract_files
    raise Exception("Unpacking command failed!")
Exception: Unpacking command failed!
```

BTW, how do you debug `QThread` in VSCode? I had try set breakpoint but not works. 

I also try `debugpy.debug_this_thread()`, in some case works, but some case the app crash, maybe the debugger crash.

**Comment by Cutleast** [comment] 2024-12-04 14:33
I suspect that 7z has issues with the archives. Could you try to extract them manually with 7z to exclude any issues with SSE-AT?

PS: Debugging is currently a bit weird in the master branch. I fixed it in the v3 branch but that one isn't usable, yet.

**Comment by GF-Huang** [comment] 2024-12-04 15:03
I got it, because the debugging working path does not contains `7z.exe`.

**Comment by Cutleast** [comment] 2024-12-04 15:08
That's another issue I fixed in the v3 branch. It should work if you set the cwd to the src folder in the launch configuration.

**Comment by Cutleast** [comment] 2024-12-04 15:22
The following launch configuration should work:
```json
			{
				"name": "Debug SSE-AT",
				"type": "debugpy",
				"request": "launch",
				"program": "${workspaceFolder}/src/app.py",
				"console": "integratedTerminal",
				"cwd": "${workspaceFolder}/src",
			}
```

**Comment by GF-Huang** [comment] 2024-12-04 15:54
I found that another issue. I'm trying build from source, but got `WinError 17` at
```
File "C:\Users\jokeh\DEV\Code\SSE-Auto-Translator\build.py", line 161, in <module>
  os.link(item, dest)
OSError: [WinError 17]
```

Because I put the source code inside my `DEV` folder, I mount it as a folder, actually it is a `Dev Drive` of Windows 11. It is `ReFS` file system, it seems not supports soft/hard link, so it cause this issue.

**Comment by Cutleast** [comment] 2024-12-04 16:24
I now pushed a fix to [this branch](https://github.com/Cutleast/SSE-Auto-Translator/tree/17-translations-for-mandarin-not-found-because-chinese-is-searched-for) for the "Chinese"/"Mandarin" issue.
I tried it myself with Adamant and now it works.
Are you able to run SSE-AT from source? If yes, can you verify that the issue is solved for the other translations, as well?

**Comment by GF-Huang** [comment] 2024-12-04 16:28
I'm trying, but there're 1500+ mods, so it will take a few time.

**Comment by GF-Huang** [comment] 2024-12-04 17:05
I think we should need some buttons to clear cache.

**Comment by Cutleast** [comment] 2024-12-04 17:06
Settings > App Settings > Scroll to the bottom

**Comment by GF-Huang** [comment] 2024-12-04 18:36
Most of them can be downloaded, and I can already generate output mod. But a little failed as below.

![image](https://github.com/user-attachments/assets/2664b7a9-4806-4308-a35c-0c14d9a791d5)
![image](https://github.com/user-attachments/assets/838e25a4-c903-445f-b3cd-a90e551b1fb5)

**Comment by Cutleast** [comment] 2024-12-04 20:33
The first error is caused by translations whose plugin(s) is/are incompatible to the one(s) from the original mod. Possible reasons for this include custom edits made to a plugin by a modlist creator (for example, turning it into a light-flagged plugin). Unfortunately there is no real solution to this, as I already tried to map them somehow but I couldn't somehow figure out, how FormIDs of light-flagged plugins are calculated compared to their pendants.

The second error is interesting. Are you able to download that file manually and see if it's a problem with the file or with an incomplete download?

**Comment by GF-Huang** [comment] 2024-12-05 05:20
> The second error is interesting. Are you able to download that file manually and see if it's a problem with the file or with an incomplete download?

It can be reproduce, but extract it by 7z.exe manually will successfully.

![image](https://github.com/user-attachments/assets/029dfc48-f831-49eb-b7e1-bef69ef83ced)

![image](https://github.com/user-attachments/assets/2df9962b-1be3-49de-b179-930a015321b4)

[Revealing Rune](https://www.nexusmods.com/skyrimspecialedition/mods/120935)
[Revealing Rune (CHS)](https://www.nexusmods.com/skyrimspecialedition/mods/121205)

**Comment by Cutleast** [comment] 2024-12-05 06:26
I'll investigate it this afternoon (UTC+1) and see if I can find out why it fails to extract it.

**Comment by GF-Huang** [comment] 2024-12-05 06:37
Maybe the mod author/uploader use wrong extension file name...

![image](https://github.com/user-attachments/assets/868de085-2341-4474-a68d-6b26630f9637)

**Comment by Cutleast** [comment] 2024-12-05 10:16
Does it work if you rename the archive to .zip and try to import the translation manually?

See [here](https://github.com/Cutleast/SSE-Auto-Translator/blob/master/doc/Instructions_en_US.md#b-database-panel-shows-installed-translations-and-the-plugins-they-cover) (button "e") on how to import a translation from disk.

**Comment by GF-Huang** [comment] 2024-12-05 11:41
You're right. Rename to `.zip`, it can be imported manually without errors.

**Comment by Cutleast** [comment] 2024-12-05 12:07
The author definitely packed the archive wrong. I'll see if I can add some detection to it to extract it despite the wrong filename suffix.

**Closed** 2024-12-06 15:13 UTC
